#default: &default
#  host: localhost
#  adapter: mysql2
#  encoding: utf8
#  pool: 5
#  username: root
#  password: admin
#  socket: /var/run/mysqld/mysqld.sock
#
#development:
#  <<: *default
#  database: super_hl7
#
#test:
#  <<: *default
#  database: super_hl7_test

#production:
#  <<: *default
#  database: green_box_production
#  username: green_box
#  password: <%= ENV['GREEN_BOX_DATABASE_PASSWORD'] %>





default: &default
  host: 10.0.80.170
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: development
  password: DevTeam01!
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: super_hl7

test:
  <<: *default
  database: super_hl7
  host: 10.0.80.170
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: development
  password: DevTeam01!
  socket: /var/run/mysqld/mysqld.sock

production:
  <<: *default
  database: green_box_production
  username: green_box
  password: <%= ENV['GREEN_BOX_DATABASE_PASSWORD'] %>